//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watson.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Family_Info = new HashSet<Family_Info>();
            this.Group_Health = new HashSet<Group_Health>();
            this.Life_Insurance = new HashSet<Life_Insurance>();
            this.Other_Insurance = new HashSet<Other_Insurance>();
            this.Vacations = new HashSet<Vacation>();
        }

        public int User_id { get; set; } = 0;
        public string EmployeeRole { get; set; }
        [MaxLength(30)]
        public string CurrentEmployer { get; set; }
        [MaxLength(40)]
        public string PreviousEmployer { get; set; }
        [MaxLength(40)]
        public string FirstName { get; set; } = "";
        [MaxLength(40)]
        public string MiddleName { get; set; } = "";
        [MaxLength(40)]
        public string LastName { get; set; } = "";
        public System.DateTime DateOfBirth { get; set; }
        [MaxLength(4)]
        public string SSN { get; set; }
        public string MartialStatus { get; set; }
        public bool Sex { get; set; }
        [MaxLength(40)]
        public string MailingAddress { get; set; }
        [MaxLength(40)]
        public string PhysicalAddress { get; set; }
        [MaxLength(30)]
        public string City { get; set; }
        [MaxLength(30)]
        public string State { get; set; }
        [MaxLength(5)]
        public string ZipCode { get; set; }
        [EmailAddress]
        public string EmailAddress { get; set; }
        [Phone]
        public string PhoneNumber { get; set; }
        [Phone]
        public string CellPhone { get; set; }
        [MaxLength(25)]
        public string County { get; set; }
        public Nullable<bool> CityLimits { get; set; }
        public System.DateTime HireDate { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public bool isActive { get; set; }
        public System.DateTime EligibilityDate { get; set; }
        public string WorkStatus { get; set; }
        public int HoursWorkedPerWeek { get; set; }
        [MaxLength(25)]
        public string JobTitle { get; set; }
        [MaxLength(9)]
        public string AnnualSalary { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family_Info> Family_Info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_Health> Group_Health { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Life_Insurance> Life_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Other_Insurance> Other_Insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacation> Vacations { get; set; }

        //internal void RemoveAt(int id)
        //{
        //    throw new NotImplementedException();
        //}
    }
}
