//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Health
    {
        public int GroupHealthInsurance_id { get; set; }
        public int Employee_id { get; set; }
        public string InsuranceCarrier { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupName { get; set; }
        public string IMSGroupNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string ReasonForGrpCoverageRefusal { get; set; }
        public string OtherCoverage { get; set; }
        public string OtherReason { get; set; }
        public string Myself { get; set; }
        public string Spouse { get; set; }
        public string Dependent { get; set; }
        public string OtherInsuranceCoverage { get; set; }
        public Nullable<System.DateTime> CafeteriaPlanYear { get; set; }
        public string NoMedicalPlan { get; set; }
        public string EmployeeOnly { get; set; }
        public string EmployeeAndSpouse { get; set; }
        public string EmployeeAndDependent { get; set; }
        public string EmployeeAndFamily { get; set; }
        public string EmployeeSignature { get; set; }
        public Nullable<System.DateTime> EmployeeSignatureDate { get; set; }
        public string EmployeeInitials { get; set; }
        public string OtherSignature { get; set; }
        public Nullable<System.DateTime> OtherSignatureDate { get; set; }
        public string NameOfPersonToReleaseInfoTo { get; set; }
        public string Relationship { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
