//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePlanDetail
    {
        public int InsurancePlanDetail_id { get; set; }
        public int InsurancePlan_id { get; set; }
        public string Item { get; set; }
        public string Detail { get; set; }
    
        public virtual InsurancePlan InsurancePlan { get; set; }
    }
}
