//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Life_Insurance
    {
        public int LifeInsurance_id { get; set; }
        public int Employee_id { get; set; }
        public string InsuranceCoverageType { get; set; }
        public System.DateTime DateOfMarriage { get; set; }
        public string SubtotalCode { get; set; }
        public string EnrollmentType { get; set; }
        public string EmployeeSignature { get; set; }
        public bool DropCoverage { get; set; }
        public bool EmployeeDentalDrop { get; set; }
        public bool SpouseDentalDrop { get; set; }
        public bool DependentDentalDrop { get; set; }
        public bool EmployeeVisionDrop { get; set; }
        public bool SpouseVisionDrop { get; set; }
        public bool DependentVisionDrop { get; set; }
        public bool DropBasicLife { get; set; }
        public bool DropEmployee { get; set; }
        public bool DropSpouse { get; set; }
        public bool DropDependents { get; set; }
        public System.DateTime Date { get; set; }
        public bool TerminationOfEmployment { get; set; }
        public bool Retirement { get; set; }
        public bool OtherEvent { get; set; }
        public bool LossOfOtherCoverage { get; set; }
        public bool CoverageLost { get; set; }
        public bool DentalCoverageLost { get; set; }
        public bool VisionCoverageLost { get; set; }
        public bool DentalCoverage { get; set; }
        public bool EmployeeOnly { get; set; }
        public bool EE_Spouse { get; set; }
        public bool EE_Dependents { get; set; }
        public bool EE_Spouse_Dependents { get; set; }
        public bool Status { get; set; }
        public bool Add { get; set; }
        public bool Drop { get; set; }
        public bool PolicyAmount { get; set; }
        public string PrimaryBeneficiaries { get; set; }
        public string ContingentBeneficiary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
